server:
  port: 8083
dubbo:
  application:
    name: dubbo-order-service-consumer
  registry:
    address: zookeeper://192.168.146.128:2181
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 1000
    retries: 3