server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: 192.168.146.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: consumer_route
          uri: http://localhost:80
          predicates:
            - Path=/order/**
#            - After=2021-06-22T20:49:11.402+08:00[Asia/Shanghai]
#            - Cookie=username,yangpeng
#            - Header=X-Request-Id,\d+ #请求头必须有X-Request-Id的属性并且值为整数
        - id: payment_route #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8002 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**  #断言,路径相匹配的进行路由

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.zict: debug
management:
  endpoint:
    consul:
      enabled: true
